### ISSUE TITLE
Change master branch to main

### ISSUE THREAD

**Issue by kbourgoin** [pystorm/streamparse#507]
I've got a bit of time to kill. Anyone opposed to me making this change? AFAICT, it will only affect Github and Read The Docs. Am I missing anything? Maybe @thornycrackers knows?

**Comment by thornycrackers** [comment]
The only thing I can think of is https://github.com/pystorm/streamparse/blob/master/.github/workflows/test.yml but it doesn't appear to specify the branch. I think you're gold

**Comment by kbourgoin** [comment]
Done!
